@echo off
IF EXIST obj rd obj /q/s
IF EXIST bin rd bin /q/s
SET KEILC_PATH=C:\Keil\UV3\UV3.exe
SET KEILC_PROJECT1=AOC_ID2008_128KFlash.Uv2
SET KEILC_PROJECT2=AOC_ID2008_256KFlash.Uv2
SET TARGET_NAME1=AOC_F22
SET TARGET_NAME2=AOC_2219Vwg

%KEILC_PATH% -r %KEILC_PROJECT2% -t %TARGET_NAME1% -o .\bin\%TARGET_NAME1%.txt
%KEILC_PATH% -r %KEILC_PROJECT2% -t %TARGET_NAME2% -o .\bin\%TARGET_NAME2%.txt



